# lifesub/deployment/manifest/services/recommend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: recommend
spec:
  selector:
    app: recommend
  ports:
    - port: 80
      targetPort: 8083
  type: ClusterIP