# lifesub/deployment/manifest/secrets/common-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: "8O2HQ13etL2BWZvYOiWsJ5uWFoLi6NBUG8divYVoCgtHVvlk3dqRksMl16toztDUeBTSIuOOPvHIrYq11G2BwQ"