# lifesub/deployment/manifest/secrets/member-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: member-secret
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "Passw0rd"
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"